# Gradle Settings
org.gradle.jvmargs=-Xmx2G -XX:+UseParallelGC -XX:MaxMetaspaceSize=1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
# Project
version=1.3.0
group=de.markusbordihn.dogscompanion
vendor_name=markusbordihn
# Mod
mod_id=dogs_companion
mod_name=Dogs Companion
mod_author=Markus Bordihn
# Hytale Configuration
hytaleHome=G:/Hytale/install/release
patchline=package/game/latest
hytaleServerJar=G:/Hytale/install/release/package/game/latest/Server/HytaleServer.jar
